name: subdominator
base: core22
version: '1.65'
summary: CLI tool for detecting subdomain takeovers
description: |
  Subdominator is an open source tool with a command line interface for identifying subdomain takeovers.
  This tool comes from StratusSecurity, an Australian security company.
  The source code is available at https://github.com/Stratus-Security/Subdominator

grade: stable
confinement: strict

architectures:
  - build-on: [amd64]
    build-for: [amd64]

apps:
  subdominator:
    command: bin/Subdominator
    plugs: [home, network]

parts:
  subdominator:
    plugin: dump
    source: bin
    organize:
      Subdominator: bin/

  # Install libicu from apt
  libicu:
    plugin: nil
    stage-packages:
      - libicu70
    override-pull: |
      apt-get update && apt-get upgrade -y
      snapcraftctl pull
